name: test aicsimageio

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: test aicsimageio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install ome-types
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install .[test]

      - name: Clone aicsimageio
        run: |
          git clone --recurse-submodules -b main https://github.com/AllenCellModeling/aicsimageio.git

      - uses: actions/cache@v3
        id: cache
        with:
          path: aicsimageio/aicsimageio/tests/resources
          key: ${{ hashFiles('aicsimageio/scripts/TEST_RESOURCES_HASH.txt') }}

      - name: Install Test Data
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install quilt3
          python .github/scripts/download_aics_test_data.py

      - name: Install aicsimageio
        run: |
          cd aicsimageio
          pip install .[test]

      - name: Run Tests
        run: |
          cd aicsimageio
          pytest aicsimageio/tests/readers/test_ome_tiff_reader.py -v -k "not REMOTE"
